In [ ]:
import pandas as pd

# Load your dataset
df = pd.read_csv('Dataset_5971_renamed_labels.csv')

df.head()

             LABEL                                               TEXT
0  Phishing Emails  Your opinion about me? 1. Over 2. Jada 3. Kusr...
1  Phishing Emails  What's up? Do you want me to come online? If y...
2  Phishing Emails                       So u workin overtime nigpun?
3  Phishing Emails  Also sir, i sent you an email about how to log...
4       Safe Email  Please Stay At Home. To encourage the notion o...

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('LABEL').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('TEXT').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['TEXT'].value_counts()
    for x_label, grp in _df_2.groupby('LABEL')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('LABEL')
_ = plt.ylabel('TEXT')

In [ ]:
import pandas as pd
import csv
import sys
from google.colab import files

# --- Step 1: Prepare for Large and Complex CSV Files ---

# Increase the CSV field size limit for very large text fields.
# This prevents errors where a single cell has too much text.
print("Setting CSV field size limit...")
try:
    max_int = sys.maxsize
    while True:
        try:
            csv.field_size_limit(max_int)
            break
        except OverflowError:
            max_int = int(max_int/10)
except Exception as e:
    print(f"Warning: Could not set CSV field size limit: {e}")

# --- Step 2: Load the Dataset with Advanced Error Handling ---

print("\nLoading 'Phishing_Email.csv'...")
try:
    # Use the 'python' engine for flexibility and 'on_bad_lines' to skip problematic rows.
    # This is the key fix to prevent the script from crashing on parsing errors.
    df = pd.read_csv(
        'Phishing_Email.csv',
        engine='python',
        on_bad_lines='warn'  # This warns about and skips bad lines instead of erroring
    )
    print("Successfully loaded the dataset. Any skipped lines due to errors were reported above.")

    # --- Step 3: Clean the Data ---

    # Drop the first column (the old index) if it exists.
    if 'Unnamed: 0' in df.columns:
        df = df.drop(columns=['Unnamed: 0'])
        print("Dropped 'Unnamed: 0' column.")

    # Rename the other columns as requested.
    df = df.rename(columns={'Email Text': 'Text', 'Email Type': 'Label'})
    print("Renamed columns to 'Text' and 'Label'.")

    # --- Step 4: Save and Download the Cleaned File ---

    output_filename = 'Phishing_Email_cleaned.csv'
    df.to_csv(output_filename, index=False)
    print(f"\nCleaned data saved to '{output_filename}'.")

    # Display the first 5 rows of the final, cleaned dataframe.
    print("\n--- First 5 Rows of Cleaned Data ---")
    print(df.head())

    # Download the file in Google Colab.
    print(f"\nAttempting to download '{output_filename}'...")
    files.download(output_filename)
    print("Download initiated successfully.")

except Exception as e:
    print(f"\n--- AN UNEXPECTED ERROR OCCURRED ---")
    print(f"Error details: {e}")
    print("\nPlease double-check that the file 'Phishing_Email.csv' is uploaded to your Colab session.")

Setting CSV field size limit...

Loading 'Phishing_Email.csv'...
Successfully loaded the dataset. Any skipped lines due to errors were reported above.
Dropped 'Unnamed: 0' column.
Renamed columns to 'Text' and 'Label'.

Cleaned data saved to 'Phishing_Email_cleaned.csv'.

--- First 5 Rows of Cleaned Data ---
                                                Text           Label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

Attempting to download 'Phishing_Email_cleaned.csv'...

Download initiated successfully.

In [ ]:
import pandas as pd
from google.colab import files # Import the files library

# Load your two datasets
df1 = pd.read_csv('Dataset_5971_renamed_labels.csv')
df2 = pd.read_csv('Phishing_Email_cleaned.csv')

# --- Step 1: Standardize Column Names ---
# The column names for the text and label were slightly different in each file.
# This step renames the columns in the second dataframe to match the first.
print("Standardizing column names...")
df2_renamed = df2.rename(columns={'Text': 'TEXT', 'Label': 'LABEL'})

# --- Step 2: Select Only the Required Columns ---
# This ensures we only work with the 'LABEL' and 'TEXT' columns from each file.
df1_subset = df1[['LABEL', 'TEXT']]
df2_subset = df2_renamed[['LABEL', 'TEXT']]

# --- Step 3: Concatenate (Combine) the Datasets ---
# This operation stacks the rows from both datasets into a single dataframe.
print("Combining the datasets...")
combined_df = pd.concat([df1_subset, df2_subset], ignore_index=True)

# --- Step 4: Save the Result ---
# The final, combined data is saved to a new CSV file.
output_filename = 'Combined_Phishing_Dataset.csv'
combined_df.to_csv(output_filename, index=False)
print(f"Successfully combined the data and saved it to '{output_filename}'")

# --- Step 5: Download the File ---
# This is the new part that triggers the download in your browser.
print(f"\nInitiating download for {output_filename}...")
files.download(output_filename)
print("Download should start shortly!")

Standardizing column names...
Combining the datasets...
Successfully combined the data and saved it to 'Combined_Phishing_Dataset.csv'

Initiating download for Combined_Phishing_Dataset.csv...

Download should start shortly!

In [ ]:
import pandas as pd
import csv
import sys

# --- Step 1: Prepare for Large and Complex CSV Files ---
# Increases the CSV field size limit for very large text fields.
print("Setting CSV field size limit...")
try:
    max_int = sys.maxsize
    while True:
        try:
            csv.field_size_limit(max_int)
            break
        except OverflowError:
            max_int = int(max_int/10)
except Exception as e:
    print(f"Warning: Could not set CSV field size limit: {e}")

# --- Step 2: Load the Dataset with Advanced Error Handling ---
# This is the key part that fixes the error.
print("\nLoading 'finaldataset.csv'...")
try:
    # We use 'engine='python'' for flexibility and 'on_bad_lines' to skip broken rows.
    data = pd.read_csv(
        'finaldataset.csv',
        engine='python',
        on_bad_lines='warn'  # This warns and skips bad lines instead of crashing
    )
    print("\nSuccessfully loaded the dataset!")

    # Display the first 5 rows to confirm it loaded correctly
    print("\n--- First 5 Rows of Loaded Data ---")
    print(data.head())

except Exception as e:
    print(f"\n--- AN ERROR OCCURRED ---")
    print(f"Error details: {e}")

Setting CSV field size limit...

Loading 'finaldataset.csv'...

Successfully loaded the dataset!

--- First 5 Rows of Loaded Data ---
             LABEL                                               TEXT
0  Phishing Emails  Your opinion about me? 1. Over 2. Jada 3. Kusr...
1  Phishing Emails  What's up? Do you want me to come online? If y...
2  Phishing Emails                       So u workin overtime nigpun?
3  Phishing Emails  Also sir, i sent you an email about how to log...
4       Safe Email  Please Stay At Home. To encourage the notion o...

In [ ]:
data.describe()

             LABEL   TEXT
count        24621  24605
unique           3  23486
top     Safe Email  empty
freq         12449    533

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24621 entries, 0 to 24620
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   LABEL   24621 non-null  object
 1   TEXT    24605 non-null  object
dtypes: object(2)
memory usage: 384.8+ KB

In [ ]:
data.columns

Index(['LABEL', 'TEXT'], dtype='object')

In [ ]:
label_counts = data['LABEL'].value_counts()
print(label_counts)

LABEL
Safe Email         12449
Phishing Email      7328
Phishing Emails     4844
Name: count, dtype: int64

In [ ]:
data['LABEL'] = data['LABEL'].replace('Phishing Email', 'Phishing Emails')
print("\nStandardized 'Phishing Email' to 'Phishing Emails'.")

    # --- 3. Show New Counts ---
    # Now we verify that the replacement worked as expected.
print("\nNew, corrected label counts:")
print(data['LABEL'].value_counts())

Standardized 'Phishing Email' to 'Phishing Emails'.

New, corrected label counts:
LABEL
Safe Email         12449
Phishing Emails    12172
Name: count, dtype: int64

In [ ]:
import pandas as pd
from google.colab import files

# Let's assume you have a DataFrame called 'df'
# df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})

# 1. Save the DataFrame to a CSV file in the Colab environment
# The index=False part prevents pandas from writing the row numbers to the file.
df.to_csv('finaldataset.csv', index=False)

# 2. Trigger the download of the file to your computer
files.download('finaldataset.csv')

In [ ]:
data=pd.read_csv(r"perfectdataset.csv")

In [ ]:
data.head()

                                                Text           Label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

In [ ]:
data.tail()

                                                    Text           Label
18645  date a lonely housewife always wanted to date ...  Phishing Email
18646  request submitted : access request for anita ....      Safe Email
18647  re : important - prc mtg hi dorn & john , as y...      Safe Email
18648  press clippings - letter on californian utilit...      Safe Email
18649                                              empty  Phishing Email

In [ ]:
data.head()

                                                Text           Label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk) (4.67.1)

In [ ]:
import pandas as pd
import nltk
import re
import csv
import sys
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
from google.colab import files

# Download necessary NLTK data
print("Downloading NLTK data...")
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
print("NLTK data download complete.")

Downloading NLTK data...
NLTK data download complete.

In [ ]:
# --- Data Cleaning ---
print("\nCleaning text data...")

def clean_text(Text):
    # Convert to lowercase
    Text = Text.lower()
    # Remove punctuation, numbers, and special characters
    Text = re.sub(r'[^a-zA-Z\s]', '', Text)
    return Text

# Handle missing values in 'Text' column by filling with an empty string
data['Text'].fillna('', inplace=True)

data['cleaned_text'] = data['Text'].apply(clean_text)

print("Text cleaning complete.")
print("\nData with 'cleaned_text' column:")
print(data[['Text', 'cleaned_text']].head())

Cleaning text data...
Text cleaning complete.

Data with 'cleaned_text' column:
                                                Text  \
0  re : 6 . 1100 , disc : uniformitarianism , re ...
1  the other side of * galicismos * * galicismo *...
2  re : equistar deal tickets are you still avail...
3  \nHello I am your hot lil horny toy.\n    I am...
4  software at incredibly low prices ( 86 % lower...

                                        cleaned_text
0  re      disc  uniformitarianism  re    sex  la...
1  the other side of  galicismos   galicismo  is ...
2  re  equistar deal tickets are you still availa...
3  \nhello i am your hot lil horny toy\n    i am ...
4  software at incredibly low prices    lower   d...

In [ ]:
# --- Tokenization ---
print("\nTokenizing cleaned text...")

data['tokens'] = data['cleaned_text'].apply(word_tokenize)

print("Tokenization complete.")
print("\nData with 'tokens' column:")
print(data[['cleaned_text', 'tokens']].head())

Tokenizing cleaned text...
Tokenization complete.

Data with 'tokens' column:
                                        cleaned_text  \
0  re      disc  uniformitarianism  re    sex  la...
1  the other side of  galicismos   galicismo  is ...
2  re  equistar deal tickets are you still availa...
3  \nhello i am your hot lil horny toy\n    i am ...
4  software at incredibly low prices    lower   d...

                                              tokens
0  [re, disc, uniformitarianism, re, sex, lang, d...
1  [the, other, side, of, galicismos, galicismo, ...
2  [re, equistar, deal, tickets, are, you, still,...
3  [hello, i, am, your, hot, lil, horny, toy, i, ...
4  [software, at, incredibly, low, prices, lower,...

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
# --- Stop Word Removal ---
print("\nRemoving stop words...")

stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

data['text_no_stopwords'] = data['cleaned_text'].apply(remove_stopwords)

print("Stop word removal complete.")
print("\nData with 'text_no_stopwords' column:")
print(data[['cleaned_text', 'text_no_stopwords']].head())

Removing stop words...
Stop word removal complete.

Data with 'text_no_stopwords' column:
                                        cleaned_text  \
0  re      disc  uniformitarianism  re    sex  la...
1  the other side of  galicismos   galicismo  is ...
2  re  equistar deal tickets are you still availa...
3  \nhello i am your hot lil horny toy\n    i am ...
4  software at incredibly low prices    lower   d...

                                   text_no_stopwords
0  [r, e,  ,  ,  ,  ,  ,  , c,  ,  , u, n, f, r, ...
1  [h, e,  , h, e, r,  , e,  , f,  ,  , g, l, c, ...
2  [r, e,  ,  , e, q, u, r,  , e, l,  , c, k, e, ...
3  [\n, h, e, l, l,  ,  ,  , u, r,  , h,  , l, l,...
4  [f, w, r, e,  ,  , n, c, r, e, b, l,  , l, w, ...

In [ ]:
data.head()

,Text,Label,cleaned_text,tokens,text_no_stopwords
0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email,re disc uniformitarianism re sex la...,"[re, disc, uniformitarianism, re, sex, lang, d...","[r, e, , , , , , , c, , , u, n, f, r, ..."
1,the other side of * galicismos * * galicismo *...,Safe Email,the other side of galicismos galicismo is ...,"[the, other, side, of, galicismos, galicismo, ...","[h, e, , h, e, r, , e, , f, , , g, l, c, ..."
2,re : equistar deal tickets are you still avail...,Safe Email,re equistar deal tickets are you still availa...,"[re, equistar, deal, tickets, are, you, still,...","[r, e, , , e, q, u, r, , e, l, , c, k, e, ..."
3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email,\nhello i am your hot lil horny toy\n i am ...,"[hello, i, am, your, hot, lil, horny, toy, i, ...","[\n, h, e, l, l, , , , u, r, , h, , l, l,..."
4,software at incredibly low prices ( 86 % lower...,Phishing Email,software at incredibly low prices lower d...,"[software, at, incredibly, low, prices, lower,...","[f, w, r, e, , , n, c, r, e, b, l, , l, w, ..."

In [ ]:
data = data[['Label', 'cleaned_text']]
print("DataFrame after dropping columns:")
print(data.head())

DataFrame after dropping columns:
            Label                                       cleaned_text
0      Safe Email  re      disc  uniformitarianism  re    sex  la...
1      Safe Email  the other side of  galicismos   galicismo  is ...
2      Safe Email  re  equistar deal tickets are you still availa...
3  Phishing Email  \nhello i am your hot lil horny toy\n    i am ...
4  Phishing Email  software at incredibly low prices    lower   d...

In [ ]:
# --- Stemming ---
print("\nStemming text...")

stemmer = PorterStemmer()

def stem_tokens(tokens):
    return [stemmer.stem(word) for word in tokens]

data['stemmed_text'] = data['cleaned_text'].apply(stem_tokens)

print("Stemming complete.")
print("\nData with 'stemmed_text' column:")
print(data[['cleaned_text', 'stemmed_text']].head())

Stemming text...
Stemming complete.

Data with 'stemmed_text' column:
                                        cleaned_text  \
0  re      disc  uniformitarianism  re    sex  la...
1  the other side of  galicismos   galicismo  is ...
2  re  equistar deal tickets are you still availa...
3  \nhello i am your hot lil horny toy\n    i am ...
4  software at incredibly low prices    lower   d...

                                        stemmed_text
0  [r, e,  ,  ,  ,  ,  ,  , d, i, s, c,  ,  , u, ...
1  [t, h, e,  , o, t, h, e, r,  , s, i, d, e,  , ...
2  [r, e,  ,  , e, q, u, i, s, t, a, r,  , d, e, ...
3  [\n, h, e, l, l, o,  , i,  , a, m,  , y, o, u,...
4  [s, o, f, t, w, a, r, e,  , a, t,  , i, n, c, ...

/tmp/ipython-input-862192863.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['stemmed_text'] = data['cleaned_text'].apply(stem_tokens)

In [ ]:
data.head()

,Label,cleaned_text,stemmed_text
0,Safe Email,re disc uniformitarianism re sex la...,"[r, e, , , , , , , d, i, s, c, , , u, ..."
1,Safe Email,the other side of galicismos galicismo is ...,"[t, h, e, , o, t, h, e, r, , s, i, d, e, , ..."
2,Safe Email,re equistar deal tickets are you still availa...,"[r, e, , , e, q, u, i, s, t, a, r, , d, e, ..."
3,Phishing Email,\nhello i am your hot lil horny toy\n i am ...,"[\n, h, e, l, l, o, , i, , a, m, , y, o, u,..."
4,Phishing Email,software at incredibly low prices lower d...,"[s, o, f, t, w, a, r, e, , a, t, , i, n, c, ..."

In [ ]:
data = data[['Label', 'cleaned_text']]
print("DataFrame after dropping columns:")
print(data.head())

DataFrame after dropping columns:
            Label                                       cleaned_text
0      Safe Email  re      disc  uniformitarianism  re    sex  la...
1      Safe Email  the other side of  galicismos   galicismo  is ...
2      Safe Email  re  equistar deal tickets are you still availa...
3  Phishing Email  \nhello i am your hot lil horny toy\n    i am ...
4  Phishing Email  software at incredibly low prices    lower   d...

In [ ]:
# --- Lemmatization ---
print("\nLemmatizing text...")

lemmatizer = WordNetLemmatizer()

def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

data['lemmatized_text'] = data['cleaned_text'].apply(lemmatize_tokens)

print("Lemmatization complete.")
print("\nData with 'lemmatized_text' column:")
print(data[['cleaned_text', 'lemmatized_text']].head())

Lemmatizing text...
Lemmatization complete.

Data with 'lemmatized_text' column:
                                        cleaned_text  \
0  re      disc  uniformitarianism  re    sex  la...
1  the other side of  galicismos   galicismo  is ...
2  re  equistar deal tickets are you still availa...
3  \nhello i am your hot lil horny toy\n    i am ...
4  software at incredibly low prices    lower   d...

                                     lemmatized_text
0  [r, e,  ,  ,  ,  ,  ,  , d, i, s, c,  ,  , u, ...
1  [t, h, e,  , o, t, h, e, r,  , s, i, d, e,  , ...
2  [r, e,  ,  , e, q, u, i, s, t, a, r,  , d, e, ...
3  [\n, h, e, l, l, o,  , i,  , a, m,  , y, o, u,...
4  [s, o, f, t, w, a, r, e,  , a, t,  , i, n, c, ...

In [ ]:
data = data[['Label', 'cleaned_text']]
print("DataFrame after dropping columns:")
print(data.head())

DataFrame after dropping columns:
            Label                                       cleaned_text
0      Safe Email  re      disc  uniformitarianism  re    sex  la...
1      Safe Email  the other side of  galicismos   galicismo  is ...
2      Safe Email  re  equistar deal tickets are you still availa...
3  Phishing Email  \nhello i am your hot lil horny toy\n    i am ...
4  Phishing Email  software at incredibly low prices    lower   d...

In [ ]:
# --- Save and Download ---
print("\nSaving the fully processed dataset...")

# Creating a final processed text string for easy use
data['final_processed_text'] = data['cleaned_text'].apply(lambda tokens: ' '.join(tokens))

output_filename = 'perfectdataset_processed.csv'
data.to_csv(output_filename, index=False)

print(f"Processed data saved to '{output_filename}'.")

# Trigger the download
files.download(output_filename)

Saving the fully processed dataset...
Processed data saved to 'perfectdataset_processed.csv'.